name: boule
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.14
  - pip
  - make
  # Run
  - numpy
  - attrs
  - scipy
  # Build
  - python-build
  - twine
  # Test
  - pytest
  - pytest-cov
  - coverage
  - pymap3d>=2.9
  # Documentation
  - sphinx==7.2.*
  - numpydoc==1.7.*
  - sphinx-book-theme==1.1.*
  - sphinx-copybutton==0.5.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  - ensaio
  - verde
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - pygmt==0.18.*
  - gmt==6.5.*
  - ipython
  # Style
  - ruff
  - zizmor
  - burocrata
