# Copyright (c) 2019 The Boule Developers.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause
#
# This code is part of the Fatiando a Terra project (https://www.fatiando.org)
#
"""
Representation of an oblate ellipsoid with homogeneous density.
"""

import textwrap

import attrs
import numpy as np

from ._constants import G
from ._ellipsoid import (
    Centrifugal,
    CoordinateConversion,
    GeometricProperties,
    check_coordinate_system,
    to_cartesian,
    validate_flattening,
    validate_semimajor_axis,
)


@attrs.frozen()
class HomogeneousEllipsoid(GeometricProperties, CoordinateConversion, Centrifugal):
    """
    Bla.
    """

    name = attrs.field()
    semimajor_axis = attrs.field(validator=validate_semimajor_axis)
    flattening = attrs.field(validator=validate_flattening)
    density = attrs.field()
    angular_velocity = attrs.field()
    long_name = attrs.field(default=None)
    reference = attrs.field(default=None)
    comments = attrs.field(default=None)

    def __str__(self):
        """
        Define a string representation of this class.
        """
        s = self.name + " - " + self.long_name + "\n"
        s += "Homogeneous oblate ellipsoid:\n"
        s += f"  • Semimajor axis: {self.semimajor_axis} m\n"
        s += f"  • Flattening: {self.flattening}\n"
        s += f"  • Density: {self.density} kg/m³\n"
        s += f"  • Angular velocity: {self.angular_velocity} rad/s"
        if self.reference is not None:
            s += "\nSource:"
            for ref in self.reference.splitlines():
                s += "\n" + textwrap.fill(
                    ref, width=72, initial_indent=2 * " ", subsequent_indent=4 * " "
                )
        if self.comments is not None:
            s += "\nComments:\n"
            s += textwrap.fill(
                self.comments,
                width=72,
                initial_indent=2 * " ",
                subsequent_indent=2 * " ",
            )
        return s

    @property
    def mass(self):
        r"""
        The mass of the ellipsoid.

        Definition: :math:`M = V \rho`, in which :math:`V` is the volume and
        :math:`\rho` if the density.

        Units: :math:`kg`.
        """
        return self.density * self.volume

    # Gravity calculations
    # ##################################################################################

    def normal_gravitation_vector(
        self, coordinates, *, coordinate_system="geodetic", si_units=False
    ):
        r"""
        Calculate the normal gravitation vector of the ellipsoid.

        Computes the gradient vector of the :term:`gravitational potential`
        generated by this ellipsoid at **any point outside the ellipsoid**.
        Based on the closed-form expressions by [Clark1986]_ and [Takahashi2017]_.

        .. caution::

            These expressions are only valid for heights on or above the
            surface of the ellipsoid.

        Parameters
        ----------
        coordinates : tuple = (coordinate1, coordinate2, coordinate3)
            Tuple with 3 arrays containing the coordinates of the computation points.
            The meaning of the arrays is determined by the ``coordinate_system``
            argument: longitude, geodetic latitude, and geometric height for a geodetic
            system; longitude, geocentric latitude, and radius for a geocentric
            spherical system; longitude, reduced latitude, and u for an ellipsoidal
            harmonic system; x, y, and z for a geocentric Cartesian system. Each
            element can be a single number or an array. The shape of the arrays must be
            compatible. Longitude and latitudes must be in degrees and height, radius,
            and u in meters. Since longitude is not used in computations (the potential
            is symmetric with longitude), it can be assigned ``None``.
        coordinate_system : str
            The coordinate system that will be assumed for the given coordinates. Should
            be one of: ``"geodetic"`` (default), ``"spherical"``, ``"cartesian"``, or
            ``"ellipsoidal harmonic"``.
        si_units : bool
            Return the value in mGal (False, default) or m/s² (True).

        Returns
        -------
        gravitation_vector : tuple = (gx, gy, gz)
            Tuple with arrays representing the 3 components of the gravitation
            vector in the geocentric Cartesian system in mGal or m/s².

        Notes
        -----
        .. note::

            Since the calculations happen in geocentric Cartesian coordinates,
            passing inputs in any other coordinate system will require
            conversion, which may slow down computations if done in a loop.
        """
        check_coordinate_system(coordinate_system)
        x, y, z = to_cartesian(coordinates, coordinate_system, self)
        # Calculates the largest root of the equation for lambda in Takahashi
        # et. al. (2017; https://doi.org/10.5194/gmd-10-3591-2017).
        p1 = self.semiminor_axis**2 + self.semimajor_axis**2 - x**2 - y**2 - z**2
        p0 = (
            self.semiminor_axis**2 * self.semimajor_axis**2
            - self.semiminor_axis**2 * np.hypot(x, y) ** 2
            - self.semimajor_axis**2 * z**2
        )
        lamb = (-p1 + np.sqrt(p1**2 - 4 * p0)) / 2
        # Terms used all the 3 components
        const = (
            2 * np.pi * G * self.density * self.semiminor_axis * self.semimajor_axis**2
        ) / np.sqrt((self.semimajor_axis**2 - self.semiminor_axis**2) ** 3)
        atan2 = np.arctan2(
            np.sqrt(self.semimajor_axis**2 - self.semiminor_axis**2),
            np.sqrt(self.semiminor_axis**2 + lamb),
        )
        horizontal_term = const * (
            np.sqrt(
                (self.semimajor_axis**2 - self.semiminor_axis**2)
                * (self.semiminor_axis**2 + lamb)
            )
            / (self.semimajor_axis**2 + lamb)
            - atan2
        )
        gx = x * horizontal_term
        gy = y * horizontal_term
        gz = (
            z
            * 2
            * const
            * (
                atan2
                - np.sqrt(
                    (self.semimajor_axis**2 - self.semiminor_axis**2)
                    / (self.semiminor_axis**2 + lamb)
                )
            )
        )
        # convert from si to mgal
        if not si_units:
            gx *= 1e5
            gy *= 1e5
            gz *= 1e5
        return (gx, gy, gz)

    def normal_gravitation(
        self, coordinates, *, coordinate_system="geodetic", si_units=False
    ):
        r"""
        Calculate the normal gravitation of the ellipsoid.

        Computes the magnitude of the gradient of the :term:`gravitational
        potential` generated by this ellipsoid at **any point outside the
        ellipsoid**. Based on the closed-form expressions by [Clark1986]_ and
        [Takahashi2017]_.

        .. caution::

            These expressions are only valid for heights on or above the
            surface of the ellipsoid.

        Parameters
        ----------
        coordinates : tuple = (coordinate1, coordinate2, coordinate3)
            Tuple with 3 arrays containing the coordinates of the computation points.
            The meaning of the arrays is determined by the ``coordinate_system``
            argument: longitude, geodetic latitude, and geometric height for a geodetic
            system; longitude, geocentric latitude, and radius for a geocentric
            spherical system; longitude, reduced latitude, and u for an ellipsoidal
            harmonic system; x, y, and z for a geocentric Cartesian system. Each
            element can be a single number or an array. The shape of the arrays must be
            compatible. Longitude and latitudes must be in degrees and height, radius,
            and u in meters. Since longitude is not used in computations (the potential
            is symmetric with longitude), it can be assigned ``None``.
        coordinate_system : str
            The coordinate system that will be assumed for the given coordinates. Should
            be one of: ``"geodetic"`` (default), ``"spherical"``, ``"cartesian"``, or
            ``"ellipsoidal harmonic"``.
        si_units : bool
            Return the value in mGal (False, default) or m/s² (True).

        Returns
        -------
        gravitation : float or array
            The magnitude of the gravitation vector in mGal or m/s².

        Notes
        -----
        .. note::

            Since the calculations happen in geocentric Cartesian coordinates,
            passing inputs in any other coordinate system will require
            conversion, which may slow down computations if done in a loop.
        """
        gx, gy, gz = self.normal_gravitation_vector(
            coordinates, coordinate_system=coordinate_system, si_units=si_units
        )
        return np.sqrt(gx**2 + gy**2 + gz**2)

    def normal_gravity_vector(
        self, coordinates, *, coordinate_system="geodetic", si_units=False
    ):
        r"""
        Calculate the normal gravity vector of the ellipsoid.

        Computes the gradient vector of the :term:`gravity potential`
        (gravitational plus centrifugal) generated by this ellipsoid at **any
        point outside the ellipsoid**. Based on the closed-form expressions by
        [Clark1986]_ and [Takahashi2017]_.

        .. caution::

            These expressions are only valid for heights on or above the
            surface of the ellipsoid.

        Parameters
        ----------
        coordinates : tuple = (coordinate1, coordinate2, coordinate3)
            Tuple with 3 arrays containing the coordinates of the computation points.
            The meaning of the arrays is determined by the ``coordinate_system``
            argument: longitude, geodetic latitude, and geometric height for a geodetic
            system; longitude, geocentric latitude, and radius for a geocentric
            spherical system; longitude, reduced latitude, and u for an ellipsoidal
            harmonic system; x, y, and z for a geocentric Cartesian system. Each
            element can be a single number or an array. The shape of the arrays must be
            compatible. Longitude and latitudes must be in degrees and height, radius,
            and u in meters. Since longitude is not used in computations (the potential
            is symmetric with longitude), it can be assigned ``None``.
        coordinate_system : str
            The coordinate system that will be assumed for the given coordinates. Should
            be one of: ``"geodetic"`` (default), ``"spherical"``, ``"cartesian"``, or
            ``"ellipsoidal harmonic"``.
        si_units : bool
            Return the value in mGal (False, default) or m/s² (True).

        Returns
        -------
        gravity_vector : tuple = (gx, gy, gz)
            Tuple with arrays representing the 3 components of the gravity
            vector in the geocentric Cartesian system in mGal or m/s².

        Notes
        -----
        .. note::

            Since the calculations happen in geocentric Cartesian coordinates,
            passing inputs in any other coordinate system will require
            conversion, which may slow down computations if done in a loop.
        """
        gx, gy, gz = self.normal_gravitation_vector(
            coordinates, coordinate_system=coordinate_system, si_units=si_units
        )
        fx, fy, fz = self.centrifugal_acceleration(
            coordinates, coordinate_system=coordinate_system, si_units=si_units
        )
        return (gx + fx, gy + fy, gz + fz)

    def normal_gravity(
        self, coordinates, *, coordinate_system="geodetic", si_units=False
    ):
        r"""
        Calculate the normal gravity of the ellipsoid.

        Computes the magnitude of the gradient vector of the :term:`gravity
        potential` (gravitational plus centrifugal) generated by this ellipsoid
        at **any point outside the ellipsoid**. Based on the closed-form
        expressions by [Clark1986]_ and [Takahashi2017]_.

        .. caution::

            These expressions are only valid for heights on or above the
            surface of the ellipsoid.

        Parameters
        ----------
        coordinates : tuple = (coordinate1, coordinate2, coordinate3)
            Tuple with 3 arrays containing the coordinates of the computation points.
            The meaning of the arrays is determined by the ``coordinate_system``
            argument: longitude, geodetic latitude, and geometric height for a geodetic
            system; longitude, geocentric latitude, and radius for a geocentric
            spherical system; longitude, reduced latitude, and u for an ellipsoidal
            harmonic system; x, y, and z for a geocentric Cartesian system. Each
            element can be a single number or an array. The shape of the arrays must be
            compatible. Longitude and latitudes must be in degrees and height, radius,
            and u in meters. Since longitude is not used in computations (the potential
            is symmetric with longitude), it can be assigned ``None``.
        coordinate_system : str
            The coordinate system that will be assumed for the given coordinates. Should
            be one of: ``"geodetic"`` (default), ``"spherical"``, ``"cartesian"``, or
            ``"ellipsoidal harmonic"``.
        si_units : bool
            Return the value in mGal (False, default) or m/s² (True).

        Returns
        -------
        gravity : float or array
            The magnitude of the gravity vector in mGal or m/s².

        Notes
        -----
        .. note::

            Since the calculations happen in geocentric Cartesian coordinates,
            passing inputs in any other coordinate system will require
            conversion, which may slow down computations if done in a loop.
        """
        gx, gy, gz = self.normal_gravity_vector(
            coordinates, coordinate_system=coordinate_system, si_units=si_units
        )
        return np.sqrt(gx**2 + gy**2 + gz**2)
