# Build the documentation to test that it works without errors.
#
# NOTE: Pin actions to a specific commit to avoid having the authentication
# token stolen if the Action is compromised. See the comments and links here:
# https://github.com/pypa/gh-action-pypi-publish/issues/27
#
name: docs

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

# Use bash by default in all jobs
defaults:
  run:
    # The -l {0} is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    # -e makes sure builds fail if any command fails
    shell: bash -e -l {0}

jobs:
  #############################################################################
  # Build the docs
  build:
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS: env/requirements-docs.txt env/requirements-build.txt
      PYTHON: "3.14"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          # Need to fetch more than the last commit so that setuptools-scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      # Need the tags so that setuptools-scm can form a valid version number
      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5
        with:
          python-version: ${{ env.PYTHON }}
          miniforge-version: latest
          channels: conda-forge

      - name: Collect requirements
        run: |
          echo "Install Dependente to capture dependencies:"
          python -m pip install dependente==0.3.0
          echo ""
          echo "Capturing run-time dependencies:"
          dependente --source install > requirements-full.txt
          echo ""
          echo "Capturing dependencies from:"
          for requirement in $REQUIREMENTS
          do
            echo "  $requirement"
            cat $requirement >> requirements-full.txt
          done
          echo ""
          echo "Collected dependencies:"
          cat requirements-full.txt

      - name: Rename conda-forge packages
        run: |
          echo "Rename conda-forge packages in requirements-full.txt"
          # Replace "build" for "python-build"
          sed -s --in-place 's/^build$/python-build/' requirements-full.txt
          echo "Renamed dependencies:"
          cat requirements-full.txt

      - name: Setup caching for conda packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.PYTHON }}-${{ hashFiles('requirements-full.txt') }}

      - name: Install requirements
        run: conda install --quiet --file requirements-full.txt python==$PYTHON

      - name: List installed packages
        run: conda list

      - name: Build source and wheel distributions
        run: make build

      - name: Install the package
        run: pip install --no-deps dist/*.whl

      - name: Cache the Ensaio datasets
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ${{ runner.temp }}/cache/ensaio
          # Use a constant key to reuse the datasets across all jobs
          key: ensaio

      - name: Build the documentation
        run: make -C doc clean all
        env:
          # Fetch the data from the GitHub releases to avoid overloading Zenodo
          ENSAIO_DATA_FROM_GITHUB: true
          # Define directory where sample data will be stored
          ENSAIO_DATA_DIR: ${{ runner.temp }}/cache/ensaio/
